site_name: ChainAPI Docs

theme:
  name: material
  favicon: images/favicon.png
  font:
    text: Mulish
  logo: images/logo-chainapi-white.svg

copyright: >
  <a href="https://chainapi.com/privacy-policy">Privacy Policy</a><br>
  <a href="https://chainapi.com/terms-and-conditions">Terms & Conditions</a><br>
  Copyright &copy; 2023 ChainAPI, Inc.

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/chainapi
      name: ChainAPI on Twitter
    - icon: fontawesome/brands/medium
      link: https://medium.com/chainapi
      name: ChainAPI on Medium
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/chainapi
      name: ChainAPI on LinkedIn

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Introduction:
      - "What is ChainAPI?": "index.md"
      - "Why use ChainAPI?": "introduction/why-use-chainapi.md"
  - Guides:
      - Overview: "guides/overview.md"
      - Accounts: "guides/accounts.md"
      - Integrations: "guides/integrations.md"
      - Deployments: "guides/deployments.md"
      - Workspaces: "guides/workspaces.md"
      - "Import & Export OIS": "guides/import-export.md"
  - Reference:
      - Airnode: "reference/terms/#airnode"
      - API Card: "reference/terms/#api-card"
      - Base URL: "reference/terms/#base-url"
      - Blockchain Providers: "reference/terms/#blockchain-providers"
      - Cloud Provider: "reference/terms/#cloud-provider"
      - Deployment: "reference/terms/#deployment"
      - Endpoint: "reference/terms/#endpoint"
      - Heartbeat: "reference/terms/#heartbeat"
      - HTTP: "reference/terms/#http"
      - Integration: "reference/terms/#integration"
      - Mainnet: "reference/terms/#mainnet"
      - Mnemonic: "reference/terms/#mnemonic"
      - Parameters: "reference/terms/#parameters"
      - Path: "reference/terms/#path"
      - Reserved Parameters: "reference/terms/#reserved-parameters"
      - Security Schemes: "reference/terms/#security-schemes"
      - Versioning: "reference/terms/#versioning"
