site_name: ChainAPI Docs

theme:
  name: material
  favicon: images/favicon.png
  font:
    text: Mulish
  logo: images/logo-chainapi-white.svg

copyright: Copyright &copy; 2023 ChainAPI, Inc.

extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/chainapi
      name: ChainAPI on Twitter
    - icon: fontawesome/brands/medium
      link: https://medium.com/chainapi
      name: ChainAPI on Medium
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/chainapi
      name: ChainAPI on LinkedIn

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Introduction:
      - "What is ChainAPI?": "index.md"
      - "Why use ChainAPI?": "introduction/why-use-chainapi.md"
  - Guides:
      - Overview: "guides/overview.md"
      - Accounts: "guides/accounts.md"
      - Integrations: "guides/integrations.md"
      - Deployments: "guides/deployments.md"
      - Workspaces: "guides/workspaces.md"
      - "Import & Export OIS": "guides/import-export.md"
